// <auto-generated />
using System;
using MarketMonitorService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketMonitorService.Infrastructure.Migrations
{
    [DbContext(typeof(MarketMonitorDbContext))]
    [Migration("20260710015442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketMonitorService.Infrastructure.Persistence.CooldownRow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol", "Market");

                    b.ToTable("cooldown", (string)null);
                });

            modelBuilder.Entity("MarketMonitorService.Infrastructure.Persistence.MonitorSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("monitor_settings", (string)null);
                });

            modelBuilder.Entity("MarketMonitorService.Infrastructure.Persistence.PriceBaselineRow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol", "Market");

                    b.ToTable("price_baseline", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
