<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>InformationCollectionService.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InformationCollectionService.Domain\InformationCollectionService.Domain.csproj" />
  </ItemGroup>
</Project>
