// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportService.Infrastructure.Persistence;

#nullable disable

namespace ReportService.Infrastructure.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportService.Infrastructure.Persistence.PolicyRevisionAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("JstDate")
                        .HasColumnType("date");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ReportVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WatchlistAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WatchlistApplyJson")
                        .HasColumnType("text");

                    b.Property<string>("WatchlistChangesJson")
                        .HasColumnType("text");

                    b.Property<string>("WatchlistSnapshotJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JstDate");

                    b.HasIndex("PeriodKey", "ReportVersion");

                    b.ToTable("policy_revision_attempts", (string)null);
                });

            modelBuilder.Entity("ReportService.Infrastructure.Persistence.ReportRow", b =>
                {
                    b.Property<string>("PeriodKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AssumptionsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("BasedOn")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PolicySummary")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<int>("ReviewState")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UnsuppliedInputs")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("PeriodKey");

                    b.HasIndex("Kind", "State", "PeriodStart");

                    b.ToTable("reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
