// <auto-generated />
using System;
using OrderExecutionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OrderExecutionService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderExecutionDbContext))]
    partial class OrderExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderExecutionService.Infrastructure.Persistence.ExecutedOrderRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("PositionEffect")
                        .HasColumnType("integer");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<decimal>("SlippageRatio")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("OrderId");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("executed_orders", (string)null);
                });

            modelBuilder.Entity("OrderExecutionService.Infrastructure.Persistence.OrderDispatchReservationRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("DecisionId");

                    b.HasIndex("State");

                    b.HasIndex("State", "CompletedAt");

                    b.ToTable("order_dispatch_reservations", (string)null);
                });

            modelBuilder.Entity("OrderExecutionService.Infrastructure.Persistence.OrderLifecycleEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("PreviousPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("PreviousQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("OrderId", "OccurredAt");

                    b.ToTable("order_lifecycle_events", (string)null);
                });

            modelBuilder.Entity("OrderExecutionService.Infrastructure.Persistence.ProtectiveStopOrderRow", b =>
                {
                    b.Property<Guid>("EntryDecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrySide")
                        .HasColumnType("integer");

                    b.Property<decimal>("FxRateToBase")
                        .HasColumnType("numeric");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("StopDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StopOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TriggerPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntryDecisionId");

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("protective_stop_orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
