// <auto-generated />
using System;
using RiskManagementService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RiskManagementService.Infrastructure.Migrations
{
    [DbContext(typeof(RiskManagementDbContext))]
    [Migration("20260808105717_AddGoodFaithViolationClearances")]
    partial class AddGoodFaithViolationClearances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.ApprovedOrderRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FxRateToBase")
                        .HasColumnType("numeric");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("PositionEffect")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLossPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DecisionId");

                    b.ToTable("approved_orders", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.BuyInInferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BanUntil")
                        .HasColumnType("date");

                    b.Property<int>("BrokerShortQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("InFlightCloseQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("InferredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("InferredOn")
                        .HasColumnType("date");

                    b.Property<int>("LedgerShortQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<int>("NewlyInferredQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnexplainedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InferredOn");

                    b.HasIndex("Symbol", "Market");

                    b.ToTable("buy_in_inferences", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.GoodFaithViolationClearanceRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ClearedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClearedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("OrderId");

                    b.ToTable("good_faith_violation_clearances", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.GoodFaithViolationRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<decimal>("PurchaseAmountInBase")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SettledCashInBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("OrderId");

                    b.HasIndex("OccurredOn");

                    b.ToTable("good_faith_violations", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.KillSwitchRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Engaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("kill_switch", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.LockoutRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateOnly>("ReleaseOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("lockout", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.OrderActivityRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AmendmentCount")
                        .HasColumnType("integer");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DecisionId");

                    b.HasIndex("Symbol", "Market", "PlacedAt");

                    b.ToTable("order_activity", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.OrderScreeningObservationRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CountsTowardStage1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsControlViolation")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.HasKey("DecisionId");

                    b.HasIndex("CountsTowardStage1", "IsControlViolation");

                    b.ToTable("order_screening_observations", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.PauseRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("pause", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.PositionDriftStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveCount")
                        .HasColumnType("integer");

                    b.Property<string>("ObservedSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportedSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("position_drift_state", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.PositionObservationDayRow", b =>
                {
                    b.Property<DateOnly>("TradingDay")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TradingDay");

                    b.ToTable("position_observation_days", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.RiskSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("risk_settings", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.SettingsChangeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.ToTable("settings_change_log", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.Stage1FillObservationRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CountsTowardStage1")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PositionEffect")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SessionDateEasternTime")
                        .HasColumnType("date");

                    b.HasKey("DecisionId");

                    b.HasIndex("CountsTowardStage1");

                    b.ToTable("stage1_fill_observations", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.Stage1SessionUptimeRow", b =>
                {
                    b.Property<DateOnly>("SessionDateEasternTime")
                        .HasColumnType("date");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("LastObservedMinuteOfDayEasternTime")
                        .HasColumnType("integer");

                    b.Property<bool>("MeetsUptimeThreshold")
                        .HasColumnType("boolean");

                    b.Property<int>("OperationalMinutesBeforeEarlyClose")
                        .HasColumnType("integer");

                    b.Property<int>("OperationalMinutesBeforeRegularClose")
                        .HasColumnType("integer");

                    b.Property<bool>("QualifiesTowardStage1")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionDateEasternTime", "Provider");

                    b.HasIndex("QualifiesTowardStage1", "MeetsUptimeThreshold");

                    b.ToTable("stage1_session_uptime", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.StagePerformanceRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("BacktestMaxDrawdownRatio")
                        .HasColumnType("numeric");

                    b.Property<bool>("BacktestPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("DailyLossLimitRespected")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ObservedMaxDrawdownRatio")
                        .HasColumnType("numeric");

                    b.Property<bool>("SlippageAndCostWithinExpected")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("stage_performance", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.StageTransitionRow", b =>
                {
                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FromStage")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("ToStage")
                        .HasColumnType("integer");

                    b.HasKey("Sequence");

                    b.ToTable("stage_transitions", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.TradeFillRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("DecisionId");

                    b.ToTable("trade_fills", (string)null);
                });

            modelBuilder.Entity("RiskManagementService.Infrastructure.Persistence.WithdrawalNotificationRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Signature")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("withdrawal_notification", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
