// <auto-generated />
using System;
using AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiStockTrading.RiskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(RiskManagementDbContext))]
    [Migration("20260711055544_AddApprovedOrderStopLoss")]
    partial class AddApprovedOrderStopLoss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.ApprovedOrderRow", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("PositionEffect")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopLossPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DecisionId");

                    b.ToTable("approved_orders", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.KillSwitchRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Engaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("kill_switch", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.LockoutRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateOnly>("ReleaseOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("lockout", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.RiskSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("risk_settings", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.SettingsChangeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.ToTable("settings_change_log", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.RiskManagement.Infrastructure.Foundation.Persistence.TradeFillRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("DecisionId");

                    b.ToTable("trade_fills", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
