<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>MarketMonitorService.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarketMonitorService.Domain\MarketMonitorService.Domain.csproj" />
  </ItemGroup>
</Project>
