<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AiStockTrading.Configuration.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConfigurationService.Domain\ConfigurationService.Domain.csproj" />
  </ItemGroup>
</Project>
