<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AiStockTrading.Report.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ReportService.Domain\ReportService.Domain.csproj" />
  </ItemGroup>
</Project>
