// <auto-generated />
using System;
using AiStockTrading.MarketMonitor.Worker.Foundation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiStockTrading.MarketMonitor.Worker.Migrations
{
    [DbContext(typeof(MarketMonitorDbContext))]
    partial class MarketMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiStockTrading.MarketMonitor.Worker.Foundation.Persistence.CooldownRow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol", "Market");

                    b.ToTable("cooldown", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.MarketMonitor.Worker.Foundation.Persistence.MonitorSettingsChangeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.ToTable("monitor_settings_change", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.MarketMonitor.Worker.Foundation.Persistence.MonitorSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("monitor_settings", (string)null);
                });

            modelBuilder.Entity("AiStockTrading.MarketMonitor.Worker.Foundation.Persistence.PriceBaselineRow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Market")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol", "Market");

                    b.ToTable("price_baseline", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
