<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AiStockTrading.Backtest.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BacktestService.Domain\BacktestService.Domain.csproj" />
  </ItemGroup>
</Project>
