<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>AiStockTrading.OrderExecution.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrderExecutionService.Domain\OrderExecutionService.Domain.csproj" />
  </ItemGroup>
</Project>
